<a href="https://colab.research.google.com/github/ABUBAKAR755/Corvit_AI_Course/blob/main/NumPy_Tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
# 1. Create a NumPy Array
array1 = np.arange(1, 11)
print("1D Array:", array1)


1D Array: [ 1  2  3  4  5  6  7  8  9 10]


In [3]:
# 2. Array of Zeros
zeros_array = np.zeros((3, 3))
print("3x3 Zeros Array:\n", zeros_array)


3x3 Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
# 3. Array of Random Numbers
random_array = np.random.randint(10, 51, size=(2, 5))
print("2x5 Random Integers (10 to 50):\n", random_array)


2x5 Random Integers (10 to 50):
 [[40 37 10 47 35]
 [38 50 11 47 29]]


In [5]:
# 4. Array Shape and Size
print("Shape:", array1.shape)
print("Size:", array1.size)


Shape: (10,)
Size: 10


In [6]:
# 5. Reshape an Array
reshaped_array = np.arange(12).reshape(3, 4)
print("3x4 Reshaped Array:\n", reshaped_array)


3x4 Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
# 6. Element-wise Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [8]:
# 7. Slicing and Indexing
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Second row:", matrix[1])
print("Third column:", matrix[:, 2])


Second row: [4 5 6]
Third column: [3 6 9]


In [10]:
# 8. Find Maximum and Minimum
print("Max:", matrix.max())
print("Min:", matrix.min())


Max: 9
Min: 1


In [11]:
# 9. Sum and Mean
print("Sum:", matrix.sum())
print("Mean:", matrix.mean())


Sum: 45
Mean: 5.0


In [12]:
# 10. Matrix Multiplication
mat1 = np.array([[1, 2],
                 [3, 4]])
mat2 = np.array([[5, 6],
                 [7, 8]])
result = np.dot(mat1, mat2)
print("Matrix Multiplication Result:\n", result)


Matrix Multiplication Result:
 [[19 22]
 [43 50]]
